apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: racket-db
spec:
  instances: 3

  bootstrap:
    initdb:
      database: racket
      owner: admin

  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true

  managed:
    roles:
    - name: admin
      ensure: present
      login: true
      superuser: true
      passwordSecret:
        name: racket-db-admin
    - name: user
      ensure: present
      login: true
      passwordSecret:
        name: racket-db-user
