CREATE TABLE "users" (
  "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  "email" VARCHAR(40) NOT NULL UNIQUE,
  "first_name" VARCHAR(16),
  "last_name" VARCHAR(40),
  "created" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY("id")
);

CREATE TABLE "goals" (
  "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  "title" VARCHAR(64),
  "created" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "finished" TIMESTAMPTZ,
  PRIMARY KEY("id")
);

CREATE TABLE "user_goals" (
  "user_id" INTEGER NOT NULL,
  "goal_id" INTEGER NOT NULL,
  PRIMARY KEY("user_id", "goal_id")
);

CREATE TABLE "goal_relations" (
  "parent_id" INTEGER NOT NULL,
  "child_id" INTEGER NOT NULL,
  PRIMARY KEY("parent_id", "child_id")
);

ALTER TABLE "user_goals"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "user_goals"
ADD FOREIGN KEY("goal_id") REFERENCES "goals"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "goal_relations"
ADD FOREIGN KEY("parent_id") REFERENCES "goals"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "goal_relations"
ADD FOREIGN KEY("child_id") REFERENCES "goals"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- Grant permissions for Hasura user
-- GRANT CREATE ON DATABASE plan TO "user"; -- Commented out: causes issues with Atlas dev DB validation
GRANT USAGE ON SCHEMA public TO "user";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "user";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "user";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "user";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "user";

-- Row Level Security Policies moved to Hasura UI
-- RLS policies are now managed through Hasura Console for easier maintenance
