apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: racket-db-user-secret
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: racket-db-user
    creationPolicy: Owner
    template:
      mergePolicy: Merge
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        password: "{{ .password }}"
        username: "user"
        jdbc-uri: "jdbc:postgresql://racket-db-rw.racket.svc.cluster.local:5432/racket?password={{ .password }}&user=user"
        uri: "postgresql://user:{{ .password }}@racket-db-rw.racket.svc.cluster.local:5432/racket"
        pgpass: "racket-db-rw.racket.svc.cluster.local:5432:racket:user:{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: pg-password-generator
