mutation CreateGoal($title: String!, $userId: Int!) {
  insert_goals_one(object: {
    title: $title
    user_goals: {
      data: {
        user_id: $userId
      }
    }
  }) {
    id
    title
    created
    finished
  }
}
