query GetRootGoals {
  user_goals(where: {
    user: { sub: { _eq: "X-Hasura-User-Sub" } }
  }) {
    goal {
      id
      title
      created
      finished
      childRelations: goalRelationsByParentId {
        child_id
      }
    }
  }
  # Get all goal relations to determine which goals are children
  goal_relations(where: {
    _and: [
      { goalByParentId: { user_goals: { user: { sub: { _eq: "X-Hasura-User-Sub" } } } } },
      { goal: { user_goals: { user: { sub: { _eq: "X-Hasura-User-Sub" } } } } }
    ]
  }) {
    child_id
  }
}
