query GetRootGoals($userId: Int!) {
  user_goals(where: {
    user_id: { _eq: $userId },
    goal: {
      _not: {
        goal_relations: {}
      }
    }
  }) {
    goal {
      id
      title
      created
      finished
      childRelations: goalRelationsByParentId {
        child_id
      }
    }
  }
}
