query GetRootGoals($userId: Int!) {
  user_goals(where: {
    user_id: { _eq: $userId }
  }) {
    goal {
      id
      title
      created
      finished
      childRelations: goalRelationsByParentId {
        child_id
      }
    }
  }
  # Get all goal relations to determine which goals are children
  goal_relations {
    child_id
  }
}
