mutation RemoveParentRelation($childId: Int!, $parentId: Int!) {
  delete_goal_relations(
    where: {
      child_id: {_eq: $childId}
      parent_id: {_eq: $parentId}
    }
  ) {
    affected_rows
  }
}
