apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - HTTP-route.yaml
  - github-secret.yaml
  - service.yaml
  - db
  - hasura
  - kargo
  - auth-secret.yaml
patches:
  - path: patches/deployment.yaml
images:
  - name: ghcr.io/simonbrundin/racket
    newTag: "frontend-1.4.1"
