apiVersion: apps/v1
kind: Deployment
metadata:
  name: racket-app
spec:
  replicas: 2 # Starta med 2 poddar
  selector:
    matchLabels:
      app: racket-app
  template:
    metadata:
      labels:
        app: racket-app
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: racket-app
          image: ghcr.io/simonbrundin/racket
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi" # Konservativa defaults
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
