apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: acceptance-stage
  namespace: plan
spec:
  metrics:
    - name: acceptance-tests
      provider:
        job:
          spec:
            template:
              spec:
                initContainers:
                  - name: setup-dagger
                    image: alpine:3.19
                    command: [sh, -c]
                    args:
                      - |
                        apk add --no-cache curl tar
                        cd /tmp
                        curl -L https://github.com/dagger/dagger/releases/download/v0.18.17/dagger_v0.18.17_linux_amd64.tar.gz | tar xz
                        mv dagger /shared/dagger
                        chmod +x /shared/dagger
                    volumeMounts:
                      - name: shared-bin
                        mountPath: /shared
                containers:
                  - name: dagger-ci
                    image: alpine:3.19
                    command: [sh, -c]
                    args:
                      - |
                        apk add --no-cache git

                        # Clone repositories
                        git clone https://github.com/simonbrundin/deployment-pipeline.git /deployment-pipeline
                        git clone https://github.com/simonbrundin/plan.git /source-repo

                        # Run Dagger pipeline
                        cd /deployment-pipeline/dagger-modules/pipeline
                        /shared/dagger call cd \
                          # --image-name YOUR_IMAGE_NAME \
                          # --registry-address YOUR_REGISTRY \
                          # --source-dir /source-repo/YOUR_SOURCE_FOLDER \
                          # --tag YOUR_TAG \
                          # --username YOUR_USERNAME \
                          # --secret env:REGISTRY_PASSWORD
                    volumeMounts:
                      - name: shared-bin
                        mountPath: /shared
                      - name: dagger-socket
                        mountPath: /run/dagger
                    env:
                      - name: DAGGER_SESSION_HOST
                        value: "127.0.0.1:8080"
                      - name: "_EXPERIMENTAL_DAGGER_RUNNER_HOST"
                        value: "unix:///run/dagger/engine.sock"
                      - name: DAGGER_CLOUD_TOKEN
                        valueFrom:
                          secretKeyRef:
                            name: dagger-cloud
                            key: token
                      - name: GITHUB_TOKEN
                        valueFrom:
                          secretKeyRef:
                            name: github-pat
                            key: token
                      - name: REGISTRY_PASSWORD
                        valueFrom:
                          secretKeyRef:
                            name: registry-secret
                            key: password
                  - name: dagger-engine
                    image: registry.dagger.io/engine:v0.18.17
                    securityContext:
                      privileged: true
                    volumeMounts:
                      - name: dagger-socket
                        mountPath: /run/dagger
                      - name: dagger-storage
                        mountPath: /var/lib/dagger
                    readinessProbe:
                      exec:
                        command: ["dagger", "core", "version"]
                      initialDelaySeconds: 5
                      periodSeconds: 5
                volumes:
                  - name: shared-bin
                    emptyDir: {}
                  - name: dagger-socket
                    emptyDir: {}
                  - name: dagger-storage
                    emptyDir: {}
                restartPolicy: Never
            backoffLimit: 1
