-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" varchar(40) NOT NULL,
	"first_name" varchar(16),
	"last_name" varchar(40),
	"created" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "users_email_key" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "goals" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "goals_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(64),
	"created" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"finished" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "user_goals" (
	"user_id" integer NOT NULL,
	"goal_id" integer NOT NULL,
	CONSTRAINT "user_goals_pkey" PRIMARY KEY("user_id","goal_id")
);
--> statement-breakpoint
CREATE TABLE "goal_relations" (
	"parent_id" integer NOT NULL,
	"child_id" integer NOT NULL,
	CONSTRAINT "goal_relations_pkey" PRIMARY KEY("parent_id","child_id")
);
--> statement-breakpoint
ALTER TABLE "user_goals" ADD CONSTRAINT "user_goals_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_goals" ADD CONSTRAINT "user_goals_goal_id_fkey" FOREIGN KEY ("goal_id") REFERENCES "public"."goals"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goal_relations" ADD CONSTRAINT "goal_relations_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "public"."goals"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goal_relations" ADD CONSTRAINT "goal_relations_child_id_fkey" FOREIGN KEY ("child_id") REFERENCES "public"."goals"("id") ON DELETE no action ON UPDATE no action;
*/